ALTER TYPE "SubscriptionPlan" RENAME VALUE 'FREE' TO 'STARTER';
ALTER TYPE "SubscriptionPlan" RENAME VALUE 'BUSINESS' TO 'PROFESSIONAL';
ALTER TYPE "SubscriptionPlan" RENAME VALUE 'ACCOUNTANT' TO 'ENTERPRISE';

ALTER TABLE "WorkspaceSubscription"
  ALTER COLUMN "plan" SET DEFAULT 'STARTER';
