import { FeatureGateCard } from "@/components/billing/feature-gate-card";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { isRoleAtLeast, requireUser } from "@/lib/auth";
import { getWorkspaceFeatureAccess } from "@/lib/billing";
import { listWorkspaceClients } from "@/lib/clients";
import {
  listWorkspaceRecurringInvoices,
  processDueRecurringInvoices,
  type WorkspaceRecurringInvoice,
} from "@/lib/recurring-invoices";
import { getActiveWorkspaceMembership } from "@/lib/workspaces";
import RecurringInvoicesClient from "@/app/dashboard/recurring-invoices/_components/RecurringInvoicesClient";

export const runtime = "nodejs";

function serializeRecurringInvoice(entry: WorkspaceRecurringInvoice) {
  return {
    ...entry,
    startDate: entry.startDate.toISOString(),
    endDate: entry.endDate?.toISOString() ?? null,
    nextRunAt: entry.nextRunAt.toISOString(),
    createdAt: entry.createdAt.toISOString(),
    updatedAt: entry.updatedAt.toISOString(),
    lastGeneratedInvoice: entry.lastGeneratedInvoice
      ? {
          ...entry.lastGeneratedInvoice,
          issueDate: entry.lastGeneratedInvoice.issueDate.toISOString(),
          dueDate: entry.lastGeneratedInvoice.dueDate.toISOString(),
          createdAt: entry.lastGeneratedInvoice.createdAt.toISOString(),
        }
      : null,
  };
}

export default async function RecurringInvoicesPage() {
  const user = await requireUser();
  const membership = await getActiveWorkspaceMembership(user.id);

  if (!membership) {
    return (
      <section className="space-y-4">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold">Recurring invoices</h1>
          <p className="text-muted-foreground">No workspace assigned.</p>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Select a workspace</CardTitle>
            <CardDescription>
              Switch to a workspace to automate recurring billing.
            </CardDescription>
          </CardHeader>
        </Card>
      </section>
    );
  }

  const access = await getWorkspaceFeatureAccess(
    membership.workspaceId,
    "RECURRING_INVOICES"
  );
  if (!access.ok) {
    return (
      <section className="space-y-6">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold">Recurring invoices</h1>
          <p className="text-muted-foreground">
            Growth unlocks invoice management and recurring billing workflows.
          </p>
        </div>
        <FeatureGateCard
          feature="RECURRING_INVOICES"
          currentPlan={access.plan}
          requiredPlan={access.requiredPlan}
        />
      </section>
    );
  }

  let autoGeneratedCount = 0;
  if (isRoleAtLeast(membership.role, "MEMBER")) {
    const generationResult = await processDueRecurringInvoices(
      membership.workspaceId,
      user.id
    );
    autoGeneratedCount = generationResult.generatedCount;
  }

  const recurringInvoices = await listWorkspaceRecurringInvoices(membership.workspaceId);
  const clients = await listWorkspaceClients(membership.workspaceId);

  return (
    <RecurringInvoicesClient
      role={membership.role}
      workspaceName={membership.workspace.name}
      autoGeneratedCount={autoGeneratedCount}
      clients={clients.map((client) => ({
        id: client.id,
        displayName: client.displayName,
        email: client.email,
      }))}
      initialRecurringInvoices={recurringInvoices.map(serializeRecurringInvoice)}
    />
  );
}
