"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { formatCurrencyNGN, formatDashboardDate } from "@/lib/dashboard-formatting";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import RecurringInvoiceForm, {
  EMPTY_RECURRING_INVOICE_FORM_VALUES,
  type RecurringInvoiceFormValues,
} from "./RecurringInvoiceForm";

type Role = "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";

type ClientOption = {
  id: number;
  displayName: string;
  email: string;
};

type RecurringGeneratedInvoice = {
  id: number;
  invoiceNumber: string;
  status: "DRAFT" | "SENT" | "PAID" | "OVERDUE";
  issueDate: string;
  dueDate: string;
  totalAmount: number;
  paymentReference: string | null;
  paymentPagePath: string | null;
  createdAt: string;
};

type RecurringInvoice = {
  id: number;
  clientId: number;
  frequency: "WEEKLY" | "MONTHLY" | "QUARTERLY";
  startDate: string;
  endDate: string | null;
  nextRunAt: string;
  dueInDays: number;
  invoiceStatus: "DRAFT" | "SENT";
  paymentEnabled: boolean;
  currency: string;
  vatTreatment: "NONE" | "INPUT" | "OUTPUT" | "EXEMPT";
  whtTreatment: "NONE" | "PAYABLE" | "RECEIVABLE";
  taxCategory: string | null;
  active: boolean;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  displayName: string;
  templateItemCount: number;
  subtotal: number;
  taxAmount: number;
  totalAmount: number;
  generatedInvoiceCount: number;
  lastGeneratedInvoice: RecurringGeneratedInvoice | null;
  client: {
    id: number;
    name: string;
    companyName: string | null;
    email: string;
  };
  templateItems: Array<{
    description: string;
    quantity: number;
    unitPrice: number;
    taxRate: number;
    lineTotal: number;
  }>;
};

type Props = {
  role: Role;
  workspaceName: string;
  clients: ClientOption[];
  initialRecurringInvoices: RecurringInvoice[];
  autoGeneratedCount: number;
};

type GeneratedInvoiceNotice = {
  invoiceId: number;
  invoiceNumber: string;
  recurringInvoiceId: number;
};

function formatDate(value: string | null) {
  if (!value) return "No end date";
  return formatDashboardDate(new Date(value));
}

function sortRecurringInvoices(recurringInvoices: RecurringInvoice[]) {
  return [...recurringInvoices].sort((left, right) => {
    if (left.active !== right.active) {
      return left.active ? -1 : 1;
    }
    const dateDiff =
      new Date(left.nextRunAt).getTime() - new Date(right.nextRunAt).getTime();
    if (dateDiff !== 0) {
      return dateDiff;
    }
    return left.displayName.localeCompare(right.displayName);
  });
}

function frequencyLabel(frequency: RecurringInvoice["frequency"]) {
  switch (frequency) {
    case "WEEKLY":
      return "Weekly";
    case "MONTHLY":
      return "Monthly";
    case "QUARTERLY":
      return "Quarterly";
  }
}

function serializePayload(values: RecurringInvoiceFormValues) {
  return {
    clientId: Number(values.clientId),
    frequency: values.frequency,
    startDate: values.startDate,
    nextRunAt: values.nextRunAt,
    endDate: values.endDate || null,
    dueInDays: Number(values.dueInDays),
    invoiceStatus: values.invoiceStatus,
    paymentEnabled: values.paymentEnabled,
    currency: values.currency,
    vatTreatment: values.vatTreatment,
    whtTreatment: values.whtTreatment,
    taxCategory: values.taxCategory || null,
    active: values.active,
    notes: values.notes,
    items: values.items.map((item) => ({
      description: item.description,
      quantity: Number(item.quantity),
      unitPrice: Number(item.unitPrice),
      taxRate: Number(item.taxRate),
    })),
  };
}

function toFormValues(recurringInvoice: RecurringInvoice): RecurringInvoiceFormValues {
  return {
    clientId: String(recurringInvoice.clientId),
    frequency: recurringInvoice.frequency,
    startDate: recurringInvoice.startDate.slice(0, 10),
    nextRunAt: recurringInvoice.nextRunAt.slice(0, 10),
    endDate: recurringInvoice.endDate?.slice(0, 10) ?? "",
    dueInDays: String(recurringInvoice.dueInDays),
    invoiceStatus: recurringInvoice.invoiceStatus,
    paymentEnabled: recurringInvoice.paymentEnabled,
    currency: recurringInvoice.currency,
    vatTreatment:
      recurringInvoice.vatTreatment === "INPUT"
        ? "OUTPUT"
        : recurringInvoice.vatTreatment,
    whtTreatment: recurringInvoice.whtTreatment,
    taxCategory: recurringInvoice.taxCategory ?? "SALES_SERVICES",
    active: recurringInvoice.active,
    notes: recurringInvoice.notes ?? "",
    items: recurringInvoice.templateItems.map((item) => ({
      description: item.description,
      quantity: String(item.quantity),
      unitPrice: (item.unitPrice / 100).toFixed(2),
      taxRate: String(item.taxRate),
    })),
  };
}

export default function RecurringInvoicesClient({
  role,
  workspaceName,
  clients,
  initialRecurringInvoices,
  autoGeneratedCount,
}: Props) {
  const canEdit = role === "OWNER" || role === "ADMIN" || role === "MEMBER";
  const [recurringInvoices, setRecurringInvoices] = useState(() =>
    sortRecurringInvoices(initialRecurringInvoices)
  );
  const [editingRecurringInvoiceId, setEditingRecurringInvoiceId] = useState<number | null>(
    null
  );
  const [savingCreate, setSavingCreate] = useState(false);
  const [savingEdit, setSavingEdit] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [editError, setEditError] = useState<string | null>(null);
  const [createFormVersion, setCreateFormVersion] = useState(0);
  const [deletingId, setDeletingId] = useState<number | null>(null);
  const [generatingId, setGeneratingId] = useState<number | null>(null);
  const [generatedNotice, setGeneratedNotice] = useState<GeneratedInvoiceNotice | null>(null);

  const editingRecurringInvoice = useMemo(
    () =>
      recurringInvoices.find((entry) => entry.id === editingRecurringInvoiceId) ?? null,
    [recurringInvoices, editingRecurringInvoiceId]
  );

  const summary = useMemo(() => {
    return recurringInvoices.reduce(
      (totals, recurringInvoice) => ({
        activeCount: totals.activeCount + (recurringInvoice.active ? 1 : 0),
        totalScheduled: totals.totalScheduled + recurringInvoice.totalAmount,
        generatedInvoiceCount:
          totals.generatedInvoiceCount + recurringInvoice.generatedInvoiceCount,
      }),
      { activeCount: 0, totalScheduled: 0, generatedInvoiceCount: 0 }
    );
  }, [recurringInvoices]);

  async function handleCreate(values: RecurringInvoiceFormValues) {
    if (!canEdit) return;
    setCreateError(null);
    setActionError(null);
    setGeneratedNotice(null);
    setSavingCreate(true);

    try {
      const res = await fetch("/api/recurring-invoices", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(serializePayload(values)),
      });
      const data = await res.json();
      if (!res.ok) {
        setCreateError(data?.error ?? "Unable to create recurring invoice");
        return;
      }

      setRecurringInvoices((current) =>
        sortRecurringInvoices([data.recurringInvoice, ...current])
      );
      setCreateFormVersion((current) => current + 1);
    } catch {
      setCreateError("Network error creating recurring invoice");
    } finally {
      setSavingCreate(false);
    }
  }

  async function handleUpdate(values: RecurringInvoiceFormValues) {
    if (!canEdit || !editingRecurringInvoice) return;
    setEditError(null);
    setActionError(null);
    setGeneratedNotice(null);
    setSavingEdit(true);

    try {
      const res = await fetch(`/api/recurring-invoices/${editingRecurringInvoice.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(serializePayload(values)),
      });
      const data = await res.json();
      if (!res.ok) {
        setEditError(data?.error ?? "Unable to update recurring invoice");
        return;
      }

      setRecurringInvoices((current) =>
        sortRecurringInvoices(
          current.map((entry) =>
            entry.id === editingRecurringInvoice.id ? data.recurringInvoice : entry
          )
        )
      );
      setEditingRecurringInvoiceId(null);
    } catch {
      setEditError("Network error updating recurring invoice");
    } finally {
      setSavingEdit(false);
    }
  }

  async function handleGenerateNow(recurringInvoice: RecurringInvoice) {
    if (!canEdit) return;
    setGeneratingId(recurringInvoice.id);
    setActionError(null);
    setGeneratedNotice(null);

    try {
      const res = await fetch(`/api/recurring-invoices/${recurringInvoice.id}`, {
        method: "POST",
      });
      const data = await res.json();
      if (!res.ok) {
        setActionError(data?.error ?? "Unable to generate invoice");
        return;
      }

      setRecurringInvoices((current) =>
        sortRecurringInvoices(
          current.map((entry) =>
            entry.id === recurringInvoice.id ? data.recurringInvoice : entry
          )
        )
      );
      setGeneratedNotice({
        invoiceId: data.invoice.id,
        invoiceNumber: data.invoice.invoiceNumber,
        recurringInvoiceId: recurringInvoice.id,
      });
      if (editingRecurringInvoiceId === recurringInvoice.id) {
        setEditingRecurringInvoiceId(null);
      }
    } catch {
      setActionError("Network error generating invoice");
    } finally {
      setGeneratingId(null);
    }
  }

  async function handleDelete(recurringInvoice: RecurringInvoice) {
    if (!canEdit) return;
    const confirmed =
      typeof window === "undefined"
        ? true
        : window.confirm(
            `Delete recurring invoice for ${recurringInvoice.displayName}? This cannot be undone.`
          );
    if (!confirmed) return;

    setDeletingId(recurringInvoice.id);
    setActionError(null);
    setGeneratedNotice(null);

    try {
      const res = await fetch(`/api/recurring-invoices/${recurringInvoice.id}`, {
        method: "DELETE",
      });
      const data = await res.json();
      if (!res.ok) {
        setActionError(data?.error ?? "Unable to delete recurring invoice");
        return;
      }

      setRecurringInvoices((current) =>
        current.filter((entry) => entry.id !== recurringInvoice.id)
      );
      if (editingRecurringInvoiceId === recurringInvoice.id) {
        setEditingRecurringInvoiceId(null);
      }
    } catch {
      setActionError("Network error deleting recurring invoice");
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <section className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold">Recurring invoices</h1>
          <p className="text-muted-foreground">
            Automate repeat billing for{" "}
            <span className="font-medium text-foreground">{workspaceName}</span>.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button asChild variant="outline">
            <Link href="/dashboard/invoices/recurring/new">Dedicated create page</Link>
          </Button>
          <Button asChild variant="outline">
            <Link href="/dashboard/invoices">Open invoices</Link>
          </Button>
          <Button asChild variant="outline">
            <Link href="/dashboard/clients">Manage clients</Link>
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Total templates</CardDescription>
            <CardTitle className="text-xl">{recurringInvoices.length}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Active templates</CardDescription>
            <CardTitle className="text-xl">{summary.activeCount}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Scheduled billing</CardDescription>
            <CardTitle className="text-xl">
              {formatCurrencyNGN(summary.totalScheduled)}
            </CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Generated invoices</CardDescription>
            <CardTitle className="text-xl">{summary.generatedInvoiceCount}</CardTitle>
          </CardHeader>
        </Card>
      </div>

      {autoGeneratedCount > 0 && (
        <div className="rounded-md border border-border bg-muted/40 px-4 py-3 text-sm">
          {autoGeneratedCount} invoice{autoGeneratedCount === 1 ? "" : "s"} generated
          automatically from due recurring templates.
        </div>
      )}

      {generatedNotice && (
        <div className="rounded-md border border-border bg-muted/40 px-4 py-3 text-sm">
          Invoice{" "}
          <Link
            href={`/dashboard/invoices/${generatedNotice.invoiceId}`}
            className="font-medium underline-offset-4 hover:underline"
          >
            {generatedNotice.invoiceNumber}
          </Link>{" "}
          was generated successfully.
        </div>
      )}

      {actionError && (
        <div className="rounded-md border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
          {actionError}
        </div>
      )}

      {clients.length === 0 && (
        <Card>
          <CardHeader>
            <CardTitle>No clients available</CardTitle>
            <CardDescription>
              Add at least one client before creating a recurring billing template.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button asChild>
              <Link href="/dashboard/clients">Create a client</Link>
            </Button>
          </CardContent>
        </Card>
      )}

      <RecurringInvoiceForm
        key={createFormVersion}
        title="Create recurring invoice"
        description="Define reusable lines, tax behavior, and the schedule that should generate standard invoices."
        submitLabel="Save recurring invoice"
        clients={clients}
        initialValues={EMPTY_RECURRING_INVOICE_FORM_VALUES}
        saving={savingCreate}
        error={createError}
        disabled={!canEdit || clients.length === 0}
        onSubmit={handleCreate}
      />

      {editingRecurringInvoice && (
        <RecurringInvoiceForm
          key={`${editingRecurringInvoice.id}-${editingRecurringInvoice.updatedAt}`}
          title={`Edit ${editingRecurringInvoice.displayName}`}
          description="Update the billing schedule, tax posture, and generated invoice defaults."
          submitLabel="Update recurring invoice"
          clients={clients}
          initialValues={toFormValues(editingRecurringInvoice)}
          saving={savingEdit}
          error={editError}
          disabled={!canEdit}
          onSubmit={handleUpdate}
          onCancel={() => {
            setEditingRecurringInvoiceId(null);
            setEditError(null);
          }}
        />
      )}

      <Card>
        <CardHeader>
          <CardTitle>Recurring schedule</CardTitle>
          <CardDescription>
            Templates generate normal invoices that continue through payment links, reminders,
            ledger posting, and tax review.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {recurringInvoices.length === 0 ? (
            <div className="space-y-2">
              <p className="text-sm text-muted-foreground">
                No recurring invoices configured yet.
              </p>
              <p className="text-xs text-muted-foreground">
                Start with a weekly, monthly, or quarterly template for retainers, rent,
                or subscription billing.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="border-b">
                  <tr className="text-left">
                    <th className="pb-3 font-medium">Client</th>
                    <th className="pb-3 font-medium">Schedule</th>
                    <th className="pb-3 font-medium">Template</th>
                    <th className="pb-3 font-medium">Last generated</th>
                    <th className="pb-3 font-medium">Status</th>
                    {canEdit && <th className="pb-3 font-medium">Actions</th>}
                  </tr>
                </thead>
                <tbody>
                  {recurringInvoices.map((recurringInvoice) => (
                    <tr key={recurringInvoice.id} className="border-b last:border-b-0">
                      <td className="py-3 align-top">
                        <div className="font-medium">{recurringInvoice.displayName}</div>
                        <div className="text-xs text-muted-foreground">
                          {recurringInvoice.client.email}
                        </div>
                      </td>
                      <td className="py-3 align-top">
                        <div>{frequencyLabel(recurringInvoice.frequency)}</div>
                        <div className="text-xs text-muted-foreground">
                          Starts {formatDate(recurringInvoice.startDate)}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          Next run {formatDate(recurringInvoice.nextRunAt)}
                        </div>
                        <div className="text-xs text-muted-foreground">
                          Ends {formatDate(recurringInvoice.endDate)}
                        </div>
                      </td>
                      <td className="py-3 align-top">
                        <div>{formatCurrencyNGN(recurringInvoice.totalAmount)}</div>
                        <div className="text-xs text-muted-foreground">
                          {recurringInvoice.templateItemCount} item
                          {recurringInvoice.templateItemCount === 1 ? "" : "s"} · due in{" "}
                          {recurringInvoice.dueInDays} day(s)
                        </div>
                        <div className="text-xs text-muted-foreground">
                          Generates as {recurringInvoice.invoiceStatus.toLowerCase()} ·{" "}
                          {recurringInvoice.paymentEnabled ? "payment ready" : "manual payment link"}
                        </div>
                      </td>
                      <td className="py-3 align-top">
                        {recurringInvoice.lastGeneratedInvoice ? (
                          <div className="space-y-1">
                            <Link
                              href={`/dashboard/invoices/${recurringInvoice.lastGeneratedInvoice.id}`}
                              className="font-medium underline-offset-4 hover:underline"
                            >
                              {recurringInvoice.lastGeneratedInvoice.invoiceNumber}
                            </Link>
                            <div className="text-xs text-muted-foreground">
                              {formatDate(recurringInvoice.lastGeneratedInvoice.issueDate)} ·{" "}
                              {formatCurrencyNGN(
                                recurringInvoice.lastGeneratedInvoice.totalAmount
                              )}
                            </div>
                            <div className="text-xs text-muted-foreground">
                              {recurringInvoice.generatedInvoiceCount} generated so far
                            </div>
                          </div>
                        ) : (
                          <div className="text-xs text-muted-foreground">
                            No invoices generated yet
                          </div>
                        )}
                      </td>
                      <td className="py-3 align-top">
                        <Badge variant={recurringInvoice.active ? "secondary" : "outline"}>
                          {recurringInvoice.active ? "Active" : "Paused"}
                        </Badge>
                      </td>
                      {canEdit && (
                        <td className="py-3 align-top">
                          <div className="flex flex-wrap gap-2">
                            <Button type="button" size="sm" variant="outline" asChild>
                              <Link href={`/dashboard/invoices/recurring/${recurringInvoice.id}`}>
                                View
                              </Link>
                            </Button>
                            <Button
                              type="button"
                              size="sm"
                              variant="outline"
                              onClick={() => {
                                setEditingRecurringInvoiceId(recurringInvoice.id);
                                setEditError(null);
                              }}
                            >
                              Edit
                            </Button>
                            <Button
                              type="button"
                              size="sm"
                              variant="secondary"
                              disabled={generatingId === recurringInvoice.id}
                              onClick={() => handleGenerateNow(recurringInvoice)}
                            >
                              {generatingId === recurringInvoice.id
                                ? "Generating..."
                                : "Generate now"}
                            </Button>
                            <Button
                              type="button"
                              size="sm"
                              variant="ghost"
                              disabled={deletingId === recurringInvoice.id}
                              onClick={() => handleDelete(recurringInvoice)}
                            >
                              {deletingId === recurringInvoice.id ? "Deleting..." : "Delete"}
                            </Button>
                          </div>
                        </td>
                      )}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </section>
  );
}
