ALTER TYPE "WorkspaceAlertType" ADD VALUE IF NOT EXISTS 'UNUSUAL_EXPENSE_SPIKE';
ALTER TYPE "WorkspaceAlertType" ADD VALUE IF NOT EXISTS 'DUPLICATE_CHARGE';
ALTER TYPE "WorkspaceAlertType" ADD VALUE IF NOT EXISTS 'REVENUE_DROP';
ALTER TYPE "WorkspaceAlertType" ADD VALUE IF NOT EXISTS 'EXPENSE_CONCENTRATION';
ALTER TYPE "WorkspaceAlertType" ADD VALUE IF NOT EXISTS 'CASHFLOW_STRESS';
ALTER TYPE "WorkspaceAlertType" ADD VALUE IF NOT EXISTS 'TAX_RISK';
